### Warren Group Data Cleaning -- Buyer/Seller name cleaning/formatting
### Author: Seleeke Flingai (modified by Alexa DeRosa 1/31/2023)
### Date: 02/17/2020
### Purpose: Cleans and formats the names of buyers/sellers, particularly banks

rm(list=ls())

pacman::p_load(tidyverse, data.table, bit64)

#work
data_path = "K:/DataServices/Projects/Current_Projects/Regional_Plan_Update_Research/Speculative Investment/Data"

setwd(data_path)
list.files()

#change file name here
warren_df = fread("20240328_warren_speculative-investment-analysis-dataset.csv", stringsAsFactors = F, encoding = "Latin-1")

warren_temp = warren_df

warren_adj = warren_temp %>%
  mutate(buyer1_adj = ifelse(buyer1 %in% c('US Bank NA Tr', 'US Bk', 'US Bank NA', 'US Bk NA', 'US Bk NA Tr', 'USBk',
                                           'Us Bk', 'Us Bk NA', 'US Bk Tr', 'USA Bk', 'United States Bk', 'U S Bk NA'),
                             'US Bank',
                             ifelse(buyer1 %like% 'Wells Fargo' | buyer1 %like% 'Well Fargo'
                                    | buyer1 %like% 'Fargo Bank' | buyer1 %in% c('Wells, Fargo Bank Na', 'Fargo Bk'),
                                    'Wells Fargo Bank',
                                    ifelse(buyer1 %like% '^Deutsche' | buyer1 %in% c('Deustche Bank Natl T Co', 'America Deutsc Bk T Co Tr', 'Americas Deutsche Bk T Co',
                                                                                     'Deitsche Bk Natl T Co Tr', 'Deursche Bk Natl T Co Tr',
                                                                                     'Deustche Bk Natl T Co Tr', 'Deutache Bk Natl T Co Tr', 'Deutche Bk National T Co',
                                                                                     'Deutche Bk Natl T Co T', 'Deutshce Bk Natl T Co Tr'),
                                           'Deutsche Bank National Trust Company',
                                           ifelse(buyer1 %in% c('Bank Of America NA', 'Bank Of America NA Tr', 'Bank of America NA', 'Bk Of America NA',
                                                                'Bank of America FSB', 'Bank Of America N A', 'Bank Of America Na', 'Bank Of America Natl Assn'),
                                                  'Bank of America',
                                                  ifelse(buyer1 %like% '^HSBC',
                                                         'HSBC Bank USA',
                                                         ifelse(buyer1 %in% c('Citimortgage Inc', 'Citibank NA', 'Citibank NA Tr',
                                                                              'Citifinancial Svcs Inc', 'Citifinancial Servicing', 'Citifinancial Inc'),
                                                                'Citibank',
                                                                ifelse(buyer1 %like% 'JP Morgan' | buyer1 %like% 'JPMorgan' | buyer1 %like% 'Jpmorgan'
                                                                       | buyer1 %in% c('JP Morgan Chase Bank NA', 'JP Morgan Chase Bk', 'JP Mmorgan Chase Bk', 'JP Morgan',
                                                                                       'JP Morgan Chase Spec Mtg', 'JP Morgan Chase Bank Tr', 'JP Mmorgan Chase Bank NA',
                                                                                       'JP Morgan Acq Home Loans', 'JP Morgan Acquis Corp', 'JP Morgan Acquisit Corp', 'JP Morgan Acquisition Co',
                                                                                       'JP Morgan Cahse Bk', 'JP Morgan Chase Bank N A', 'Jp Morgan Chase Bank NA', 'JP morgan Chase Bank NA',
                                                                                       'JP Morgan Chase Bank Na', 'JP Morgan Chase Bank Na T', 'Jp Morgan Chase Bank Tr', 'Jp Morgan Chase Bk',
                                                                                       'JP morgan Chase Bk', 'Jp Morgan Chase Bk Na', 'Jp Morgan Chase Bk Tr', 'JP Morgn Chase Bk', 'JP MorganChase Bk',
                                                                                       'JP Morgan Specialty Mtg', 'JP Morgan Mtg T', 'JP Morgan Mtg Corp', 'JP Morgan Mtg Acquistion', 'JP Morgan Mtg Acquisitio',
                                                                                       'JP Morgan Mtg Acquisit Co', '	JP Morgan Mtg Acquisit 2', 'JP Morgan Mtg Acquis Corp',
                                                                                       'JP Morgan Chase Bk NA', 'Chase Home Finance LLC', 'Chase Home Fin LLC', 'Chase Home Finace LLC	',
                                                                                       'Chase Home Finance	', 'Chase Home Finance Llc', 'Chase Home Fncl LLC	', 'Chase Mahattan Bk', 'Chase Manhattan Bank USA',
                                                                                       'Chase Manhattan Mtg', 'Chase Manhattan Bk', 'Chase Manhattan Bank', 'Chas Manhattan Bk', 'Chase Manhattan Mortgage', 'Chase Manhattanmtg',
                                                                                       'Chase Mortgage Co', 'Chase Mtg', 'Chase Mtg Co', 'Chase Mtg Co West', 'Chase Mtg Holdings Inc', 'Chase Bk', 'Chase Bk TX',
                                                                                       'Chase Bk Tx', 'Jp, Morgan Chase Bank Na', 'Morgan Chase Ban Jp Tr', 'J P Morgan Chase Bank Tr',
                                                                                       'J P Morgan Chase Bank', 'J P morgan Chase Bank', 'J P Morgan Chase Bank N A'),
                                                                       'JPMorgan Chase Bank',
                                                                       ifelse(buyer1 %like% '^Morgan Stanley',
                                                                              'Morgan Stanley Investment Bank',
                                                                              ifelse(buyer1 %in% c('Wachovia Bk', 'Wachovia Mtg', 'Wachovia Mortgage Corp', 'Wachovia Bk NA Tr',
                                                                                                   'Wachovia Bk NA'),
                                                                                     'Wachovia Bank',
                                                                                     ifelse(buyer1 %in% c('Lasalle NB', 'Lasalle Natl Bk', 'Lasalle Natl Bank', 'Lasalle National Bk Tr', 'Lasalle National Bank',
                                                                                                          'Lasalle Bk Tr', 'Lasalle Bk NA Tr', 'Lasalle Bk Na Tr', 'Lasalle Bk NA', 'Lasalle Bk Na', 'Lasalle Bk',
                                                                                                          'Lasalle Bank Tr', 'Lasalle Bank Natl Assoc', 'Lasalle Bank Natl Assn Tr', 'Lasalle Bank Natl Assn T',
                                                                                                          'Lasalle Bank National, io', 'Lasalle Bank National', 'Lasalle Bank NA Tr', 'Lasalle Bank Na Tr',
                                                                                                          'LaSalle Bank NA', 'Lasalle Bank NA', 'Lasalle Bank Na', 'Lasalle Bank N A', 'Lasalle Bank'),
                                                                                            'LaSalle Bank',
                                                                                            ifelse(buyer1 %like% '^National City',
                                                                                                   'National City Bank',
                                                                                                   ifelse(buyer1 %in% c('Bank Of New York', 'Bank Of New York Tr', 'Bank Of NY', 'Bank of New York',
                                                                                                                        'Bank Of New York T Co', 'Bank Of New York Mellon', 'Bank of New York Mellon',
                                                                                                                        'Bank New York Mellon Tr', 'Bk Of New York Mellon Co', 'Bk Of New York T Co NA Tr',
                                                                                                                        'Bank 0f New York', 'Bank New York', 'Bank New York Mellon', 'Bank New York Mellon T Co',
                                                                                                                        'Bank Of New New York', 'Bank Of New York  Mellon', 'Bank Of New York Mellon T',
                                                                                                                        'Bank Of New York Melon', 'Bank Of New York T', 'Bank of New York Tr',
                                                                                                                        'Bank Of New York Tr Co Tr', 'Bank of New Yorkj', 'Bank Of New Yrok', 'Bank Of NY Mellon',
                                                                                                                        'Bank Of NY Mellon T Co Tr', 'Bank Of NY Mellon Tr', 'Bank Of York Mellon', 'Banko Of New York Mellon'),
                                                                                                          'The Bank of New York Mellon',
                                                                                                          ifelse(buyer1 %in% c("GMAC Mortgage LLC", 'GMAC Mtg Corp', 'GMAC Mortgage Corp', 'Gmac Mortgage Corp'),
                                                                                                                 'GMAC Mortgage Corp',
                                                                                                                 ifelse(buyer1 %in% c('PNC Bank NA', 'PNC Mortgage', 'PNC Bk', 'PNC Bk NA'),
                                                                                                                        'PNC Bank',
                                                                                                                        ifelse(buyer1 %in% c('Norwest Bk', 'Norwest BK', 'Norwest Bk Minn NA Tr', 'Norwest Bk Minnesota',
                                                                                                                                             'Norwest Bk Minnesota N', 'Norwest Bk Mn', 'Norwest Bk MN',
                                                                                                                                             'Norwest Bank', 'Norwest Bank Minn Na', 'Norwest Bank Minnesota', 'Norwest Bank Minnesota Na',
                                                                                                                                             'Norwest Bank MN', 'Norwest Bank Mn Na', 'Norwest Fincl Mass Inc', 'Norwest Fncl Mass',
                                                                                                                                             'Norwest Mtg', 'Norwest Mtg Corp', 'Norwest Mtg Inc'),
                                                                                                                               'Wells Fargo Bank', # Norwest Bank was acquired by Wells Fargo in 1998 and assumed the Wells Fargo name
                                                                                                                               ifelse(buyer1 %like% '^American Home Mtg',
                                                                                                                                      'American Home Mortgage',
                                                                                                                                      ifelse(buyer1 %in% c('FNMA', 'Federal National Mtg', 'Federal National Mtg Assn',
                                                                                                                                                           'Federal National Mtg Asso', '	Federal Natl Mtg', 'Federal National, ciatio',
                                                                                                                                                           'Federal Natl Mtg Assc', 'Federal Natl Mtg Assn', 'Federal Natl Mtg Assoc',
                                                                                                                                                           'Federal Ntl Mtg Assoc', 'Federal Ntl Mtg Associat', 'Federal Ntnl Mtg Assoc'), 'Federal National Mortgage Association (Fannie Mae)',
                                                                                                                                             ifelse(buyer1 %in% c('FHLM', 'FHLMC', 'Federal Home Loan Mtg', 'Federal Home Loan Mtg Cor', 'Natl FHLM', 'Fhlm',
                                                                                                                                                                  'Federal Home Loan Mortgp', 'Federal Home Loan Corp',
                                                                                                                                                                  'Federal Home Loan', 'Fed Home Loan Mtg Corp', 'fed home loan mtg corp'),
                                                                                                                                                    'Federal Home Loan Mortgage Corporation (Freddie Mac)', buyer1)))))))))))))))))),
         buyer2_adj = ifelse(buyer2 %in% c('US Bank NA Tr', 'US Bk', 'US Bank NA', 'US Bk NA', 'US Bk NA Tr', 'USBk',
                                           'Us Bk', 'Us Bk NA', 'US Bk Tr', 'USA Bk', 'United States Bk', 'U S Bk NA'),
                             'US Bank',
                             ifelse(buyer2 %like% 'Wells Fargo' | buyer2 %like% 'Well Fargo'
                                    | buyer2 %like% 'Fargo Bank' | buyer2 %in% c('Wells, Fargo Bank Na', 'Fargo Bk'),
                                    'Wells Fargo Bank',
                                    ifelse(buyer2 %like% '^Deutsche' | buyer2 %in% c('Deustche Bank Natl T Co', 'America Deutsc Bk T Co Tr', 'Americas Deutsche Bk T Co',
                                                                                     'Deitsche Bk Natl T Co Tr', 'Deursche Bk Natl T Co Tr',
                                                                                     'Deustche Bk Natl T Co Tr', 'Deutache Bk Natl T Co Tr', 'Deutche Bk National T Co',
                                                                                     'Deutche Bk Natl T Co T', 'Deutshce Bk Natl T Co Tr'),
                                           'Deutsche Bank National Trust Company',
                                           ifelse(buyer2 %in% c('Bank Of America NA', 'Bank Of America NA Tr', 'Bank of America NA', 'Bk Of America NA',
                                                                'Bank of America FSB', 'Bank Of America N A', 'Bank Of America Na', 'Bank Of America Natl Assn'),
                                                  'Bank of America',
                                                  ifelse(buyer2 %like% '^HSBC',
                                                         'HSBC Bank USA',
                                                         ifelse(buyer2 %in% c('Citimortgage Inc', 'Citibank NA', 'Citibank NA Tr',
                                                                              'Citifinancial Svcs Inc', 'Citifinancial Servicing', 'Citifinancial Inc'),
                                                                'Citibank',
                                                                ifelse(buyer2 %like% 'JP Morgan' | buyer2 %like% 'JPMorgan' | buyer2 %like% 'Jpmorgan'
                                                                       | buyer2 %in% c('JP Morgan Chase Bank NA', 'JP Morgan Chase Bk', 'JP Mmorgan Chase Bk', 'JP Morgan',
                                                                                       'JP Morgan Chase Spec Mtg', 'JP Morgan Chase Bank Tr', 'JP Mmorgan Chase Bank NA',
                                                                                       'JP Morgan Acq Home Loans', 'JP Morgan Acquis Corp', 'JP Morgan Acquisit Corp', 'JP Morgan Acquisition Co',
                                                                                       'JP Morgan Cahse Bk', 'JP Morgan Chase Bank N A', 'Jp Morgan Chase Bank NA', 'JP morgan Chase Bank NA',
                                                                                       'JP Morgan Chase Bank Na', 'JP Morgan Chase Bank Na T', 'Jp Morgan Chase Bank Tr', 'Jp Morgan Chase Bk',
                                                                                       'JP morgan Chase Bk', 'Jp Morgan Chase Bk Na', 'Jp Morgan Chase Bk Tr', 'JP Morgn Chase Bk', 'JP MorganChase Bk',
                                                                                       'JP Morgan Specialty Mtg', 'JP Morgan Mtg T', 'JP Morgan Mtg Corp', 'JP Morgan Mtg Acquistion', 'JP Morgan Mtg Acquisitio',
                                                                                       'JP Morgan Mtg Acquisit Co', '	JP Morgan Mtg Acquisit 2', 'JP Morgan Mtg Acquis Corp',
                                                                                       'JP Morgan Chase Bk NA', 'Chase Home Finance LLC', 'Chase Home Fin LLC', 'Chase Home Finace LLC	',
                                                                                       'Chase Home Finance	', 'Chase Home Finance Llc', 'Chase Home Fncl LLC	', 'Chase Mahattan Bk', 'Chase Manhattan Bank USA',
                                                                                       'Chase Manhattan Mtg', 'Chase Manhattan Bk', 'Chase Manhattan Bank', 'Chas Manhattan Bk', 'Chase Manhattan Mortgage', 'Chase Manhattanmtg',
                                                                                       'Chase Mortgage Co', 'Chase Mtg', 'Chase Mtg Co', 'Chase Mtg Co West', 'Chase Mtg Holdings Inc', 'Chase Bk', 'Chase Bk TX',
                                                                                       'Chase Bk Tx', 'Jp, Morgan Chase Bank Na', 'Morgan Chase Ban Jp Tr', 'J P Morgan Chase Bank Tr',
                                                                                       'J P Morgan Chase Bank', 'J P morgan Chase Bank', 'J P Morgan Chase Bank N A'),
                                                                       'JPMorgan Chase Bank',
                                                                       ifelse(buyer2 %like% '^Morgan Stanley',
                                                                              'Morgan Stanley Investment Bank',
                                                                              ifelse(buyer2 %in% c('Wachovia Bk', 'Wachovia Mtg', 'Wachovia Mortgage Corp', 'Wachovia Bk NA Tr',
                                                                                                   'Wachovia Bk NA'),
                                                                                     'Wachovia Bank',
                                                                                     ifelse(buyer2 %in% c('Lasalle NB', 'Lasalle Natl Bk', 'Lasalle Natl Bank', 'Lasalle National Bk Tr', 'Lasalle National Bank',
                                                                                                          'Lasalle Bk Tr', 'Lasalle Bk NA Tr', 'Lasalle Bk Na Tr', 'Lasalle Bk NA', 'Lasalle Bk Na', 'Lasalle Bk',
                                                                                                          'Lasalle Bank Tr', 'Lasalle Bank Natl Assoc', 'Lasalle Bank Natl Assn Tr', 'Lasalle Bank Natl Assn T',
                                                                                                          'Lasalle Bank National, io', 'Lasalle Bank National', 'Lasalle Bank NA Tr', 'Lasalle Bank Na Tr',
                                                                                                          'LaSalle Bank NA', 'Lasalle Bank NA', 'Lasalle Bank Na', 'Lasalle Bank N A', 'Lasalle Bank'),
                                                                                            'LaSalle Bank',
                                                                                            ifelse(buyer2 %like% '^National City',
                                                                                                   'National City Bank',
                                                                                                   ifelse(buyer2 %in% c('Bank Of New York', 'Bank Of New York Tr', 'Bank Of NY', 'Bank of New York',
                                                                                                                        'Bank Of New York T Co', 'Bank Of New York Mellon', 'Bank of New York Mellon',
                                                                                                                        'Bank New York Mellon Tr', 'Bk Of New York Mellon Co', 'Bk Of New York T Co NA Tr',
                                                                                                                        'Bank 0f New York', 'Bank New York', 'Bank New York Mellon', 'Bank New York Mellon T Co',
                                                                                                                        'Bank Of New New York', 'Bank Of New York  Mellon', 'Bank Of New York Mellon T',
                                                                                                                        'Bank Of New York Melon', 'Bank Of New York T', 'Bank of New York Tr',
                                                                                                                        'Bank Of New York Tr Co Tr', 'Bank of New Yorkj', 'Bank Of New Yrok', 'Bank Of NY Mellon',
                                                                                                                        'Bank Of NY Mellon T Co Tr', 'Bank Of NY Mellon Tr', 'Bank Of York Mellon', 'Banko Of New York Mellon'),
                                                                                                          'The Bank of New York Mellon',
                                                                                                          ifelse(buyer2 %in% c("GMAC Mortgage LLC", 'GMAC Mtg Corp', 'GMAC Mortgage Corp', 'Gmac Mortgage Corp'),
                                                                                                                 'GMAC Mortgage Corp',
                                                                                                                 ifelse(buyer2 %in% c('PNC Bank NA', 'PNC Mortgage', 'PNC Bk', 'PNC Bk NA'),
                                                                                                                        'PNC Bank',
                                                                                                                        ifelse(buyer2 %in% c('Norwest Bk', 'Norwest BK', 'Norwest Bk Minn NA Tr', 'Norwest Bk Minnesota',
                                                                                                                                             'Norwest Bk Minnesota N', 'Norwest Bk Mn', 'Norwest Bk MN',
                                                                                                                                             'Norwest Bank', 'Norwest Bank Minn Na', 'Norwest Bank Minnesota', 'Norwest Bank Minnesota Na',
                                                                                                                                             'Norwest Bank MN', 'Norwest Bank Mn Na', 'Norwest Fincl Mass Inc', 'Norwest Fncl Mass',
                                                                                                                                             'Norwest Mtg', 'Norwest Mtg Corp', 'Norwest Mtg Inc'),
                                                                                                                               'Wells Fargo Bank', # Norwest Bank was acquired by Wells Fargo in 1998 and assumed the Wells Fargo name
                                                                                                                               ifelse(buyer2 %like% '^American Home Mtg',
                                                                                                                                      'American Home Mortgage',
                                                                                                                                      ifelse(buyer2 %in% c('FNMA', 'Federal National Mtg', 'Federal National Mtg Assn',
                                                                                                                                                           'Federal National Mtg Asso', '	Federal Natl Mtg', 'Federal National, ciatio',
                                                                                                                                                           'Federal Natl Mtg Assc', 'Federal Natl Mtg Assn', 'Federal Natl Mtg Assoc',
                                                                                                                                                           'Federal Ntl Mtg Assoc', 'Federal Ntl Mtg Associat', 'Federal Ntnl Mtg Assoc'), 'Federal National Mortgage Association (Fannie Mae)',
                                                                                                                                             ifelse(buyer2 %in% c('FHLM', 'FHLMC', 'Federal Home Loan Mtg', 'Federal Home Loan Mtg Cor', 'Natl FHLM', 'Fhlm',
                                                                                                                                                                  'Federal Home Loan Mortgp', 'Federal Home Loan Corp',
                                                                                                                                                                  'Federal Home Loan', 'Fed Home Loan Mtg Corp', 'fed home loan mtg corp'), 'Federal Home Loan Mortgage Corporation (Freddie Mac)', buyer2)))))))))))))))))),
         seller1_adj = ifelse(seller1 %in% c('US Bank NA Tr', 'US Bk', 'US Bank NA', 'US Bk NA', 'US Bk NA Tr', 'USBk',
                                             'Us Bk', 'Us Bk NA', 'US Bk Tr', 'USA Bk', 'United States Bk', 'U S Bk NA'),
                              'US Bank',
                              ifelse(seller1 %like% 'Wells Fargo' | seller1 %like% 'Well Fargo'
                                     | seller1 %like% 'Fargo Bank' | seller1 %in% c('Wells, Fargo Bank Na', 'Fargo Bk'),
                                     'Wells Fargo Bank',
                                     ifelse(seller1 %like% '^Deutsche' | seller1 %in% c('Deustche Bank Natl T Co', 'America Deutsc Bk T Co Tr', 'Americas Deutsche Bk T Co',
                                                                                        'Deitsche Bk Natl T Co Tr', 'Deursche Bk Natl T Co Tr',
                                                                                        'Deustche Bk Natl T Co Tr', 'Deutache Bk Natl T Co Tr', 'Deutche Bk National T Co',
                                                                                        'Deutche Bk Natl T Co T', 'Deutshce Bk Natl T Co Tr'),
                                            'Deutsche Bank National Trust Company',
                                            ifelse(seller1 %in% c('Bank Of America NA', 'Bank Of America NA Tr', 'Bank of America NA', 'Bk Of America NA',
                                                                  'Bank of America FSB', 'Bank Of America N A', 'Bank Of America Na', 'Bank Of America Natl Assn'),
                                                   'Bank of America',
                                                   ifelse(seller1 %like% '^HSBC',
                                                          'HSBC Bank USA',
                                                          ifelse(seller1 %in% c('Citimortgage Inc', 'Citibank NA', 'Citibank NA Tr',
                                                                                'Citifinancial Svcs Inc', 'Citifinancial Servicing', 'Citifinancial Inc'),
                                                                 'Citibank',
                                                                 ifelse(seller1 %like% 'JP Morgan' | seller1 %like% 'JPMorgan' | seller1 %like% 'Jpmorgan'
                                                                        | seller1 %in% c('JP Morgan Chase Bank NA', 'JP Morgan Chase Bk', 'JP Mmorgan Chase Bk', 'JP Morgan',
                                                                                         'JP Morgan Chase Spec Mtg', 'JP Morgan Chase Bank Tr', 'JP Mmorgan Chase Bank NA',
                                                                                         'JP Morgan Acq Home Loans', 'JP Morgan Acquis Corp', 'JP Morgan Acquisit Corp', 'JP Morgan Acquisition Co',
                                                                                         'JP Morgan Cahse Bk', 'JP Morgan Chase Bank N A', 'Jp Morgan Chase Bank NA', 'JP morgan Chase Bank NA',
                                                                                         'JP Morgan Chase Bank Na', 'JP Morgan Chase Bank Na T', 'Jp Morgan Chase Bank Tr', 'Jp Morgan Chase Bk',
                                                                                         'JP morgan Chase Bk', 'Jp Morgan Chase Bk Na', 'Jp Morgan Chase Bk Tr', 'JP Morgn Chase Bk', 'JP MorganChase Bk',
                                                                                         'JP Morgan Specialty Mtg', 'JP Morgan Mtg T', 'JP Morgan Mtg Corp', 'JP Morgan Mtg Acquistion', 'JP Morgan Mtg Acquisitio',
                                                                                         'JP Morgan Mtg Acquisit Co', '	JP Morgan Mtg Acquisit 2', 'JP Morgan Mtg Acquis Corp',
                                                                                         'JP Morgan Chase Bk NA', 'Chase Home Finance LLC', 'Chase Home Fin LLC', 'Chase Home Finace LLC	',
                                                                                         'Chase Home Finance	', 'Chase Home Finance Llc', 'Chase Home Fncl LLC	', 'Chase Mahattan Bk', 'Chase Manhattan Bank USA',
                                                                                         'Chase Manhattan Mtg', 'Chase Manhattan Bk', 'Chase Manhattan Bank', 'Chas Manhattan Bk', 'Chase Manhattan Mortgage', 'Chase Manhattanmtg',
                                                                                         'Chase Mortgage Co', 'Chase Mtg', 'Chase Mtg Co', 'Chase Mtg Co West', 'Chase Mtg Holdings Inc', 'Chase Bk', 'Chase Bk TX',
                                                                                         'Chase Bk Tx', 'Jp, Morgan Chase Bank Na', 'Morgan Chase Ban Jp Tr', 'J P Morgan Chase Bank Tr',
                                                                                         'J P Morgan Chase Bank', 'J P morgan Chase Bank', 'J P Morgan Chase Bank N A'),
                                                                        'JPMorgan Chase Bank',
                                                                        ifelse(seller1 %like% '^Morgan Stanley',
                                                                               'Morgan Stanley Investment Bank',
                                                                               ifelse(seller1 %in% c('Wachovia Bk', 'Wachovia Mtg', 'Wachovia Mortgage Corp', 'Wachovia Bk NA Tr',
                                                                                                     'Wachovia Bk NA'),
                                                                                      'Wachovia Bank',
                                                                                      ifelse(seller1 %in% c('Lasalle NB', 'Lasalle Natl Bk', 'Lasalle Natl Bank', 'Lasalle National Bk Tr', 'Lasalle National Bank',
                                                                                                            'Lasalle Bk Tr', 'Lasalle Bk NA Tr', 'Lasalle Bk Na Tr', 'Lasalle Bk NA', 'Lasalle Bk Na', 'Lasalle Bk',
                                                                                                            'Lasalle Bank Tr', 'Lasalle Bank Natl Assoc', 'Lasalle Bank Natl Assn Tr', 'Lasalle Bank Natl Assn T',
                                                                                                            'Lasalle Bank National, io', 'Lasalle Bank National', 'Lasalle Bank NA Tr', 'Lasalle Bank Na Tr',
                                                                                                            'LaSalle Bank NA', 'Lasalle Bank NA', 'Lasalle Bank Na', 'Lasalle Bank N A', 'Lasalle Bank'),
                                                                                             'LaSalle Bank',
                                                                                             ifelse(seller1 %like% '^National City',
                                                                                                    'National City Bank',
                                                                                                    ifelse(seller1 %in% c('Bank Of New York', 'Bank Of New York Tr', 'Bank Of NY', 'Bank of New York',
                                                                                                                          'Bank Of New York T Co', 'Bank Of New York Mellon', 'Bank of New York Mellon',
                                                                                                                          'Bank New York Mellon Tr', 'Bk Of New York Mellon Co', 'Bk Of New York T Co NA Tr',
                                                                                                                          'Bank 0f New York', 'Bank New York', 'Bank New York Mellon', 'Bank New York Mellon T Co',
                                                                                                                          'Bank Of New New York', 'Bank Of New York  Mellon', 'Bank Of New York Mellon T',
                                                                                                                          'Bank Of New York Melon', 'Bank Of New York T', 'Bank of New York Tr',
                                                                                                                          'Bank Of New York Tr Co Tr', 'Bank of New Yorkj', 'Bank Of New Yrok', 'Bank Of NY Mellon',
                                                                                                                          'Bank Of NY Mellon T Co Tr', 'Bank Of NY Mellon Tr', 'Bank Of York Mellon', 'Banko Of New York Mellon'),
                                                                                                           'The Bank of New York Mellon',
                                                                                                           ifelse(seller1 %in% c("GMAC Mortgage LLC", 'GMAC Mtg Corp', 'GMAC Mortgage Corp', 'Gmac Mortgage Corp'),
                                                                                                                  'GMAC Mortgage Corp',
                                                                                                                  ifelse(seller1 %in% c('PNC Bank NA', 'PNC Mortgage', 'PNC Bk', 'PNC Bk NA'),
                                                                                                                         'PNC Bank',
                                                                                                                         ifelse(seller1 %in% c('Norwest Bk', 'Norwest BK', 'Norwest Bk Minn NA Tr', 'Norwest Bk Minnesota',
                                                                                                                                               'Norwest Bk Minnesota N', 'Norwest Bk Mn', 'Norwest Bk MN',
                                                                                                                                               'Norwest Bank', 'Norwest Bank Minn Na', 'Norwest Bank Minnesota', 'Norwest Bank Minnesota Na',
                                                                                                                                               'Norwest Bank MN', 'Norwest Bank Mn Na', 'Norwest Fincl Mass Inc', 'Norwest Fncl Mass',
                                                                                                                                               'Norwest Mtg', 'Norwest Mtg Corp', 'Norwest Mtg Inc'),
                                                                                                                                'Wells Fargo Bank', # Norwest Bank was acquired by Wells Fargo in 1998 and assumed the Wells Fargo name
                                                                                                                                ifelse(seller1 %like% '^American Home Mtg',
                                                                                                                                       'American Home Mortgage',
                                                                                                                                       ifelse(seller1 %in% c('FNMA', 'Federal National Mtg', 'Federal National Mtg Assn',
                                                                                                                                                             'Federal National Mtg Asso', '	Federal Natl Mtg', 'Federal National, ciatio',
                                                                                                                                                             'Federal Natl Mtg Assc', 'Federal Natl Mtg Assn', 'Federal Natl Mtg Assoc',
                                                                                                                                                             'Federal Ntl Mtg Assoc', 'Federal Ntl Mtg Associat', 'Federal Ntnl Mtg Assoc'), 'Federal National Mortgage Association (Fannie Mae)',
                                                                                                                                              ifelse(seller1 %in% c('FHLM', 'FHLMC', 'Federal Home Loan Mtg', 'Federal Home Loan Mtg Cor', 'Natl FHLM', 'Fhlm',
                                                                                                                                                                    'Federal Home Loan Mortgp', 'Federal Home Loan Corp',
                                                                                                                                                                    'Federal Home Loan', 'Fed Home Loan Mtg Corp', 'fed home loan mtg corp'), 'Federal Home Loan Mortgage Corporation (Freddie Mac)', seller1)))))))))))))))))),
         seller2_adj = ifelse(seller2 %in% c('US Bank NA Tr', 'US Bk', 'US Bank NA', 'US Bk NA', 'US Bk NA Tr', 'USBk',
                                             'Us Bk', 'Us Bk NA', 'US Bk Tr', 'USA Bk', 'United States Bk', 'U S Bk NA'),
                              'US Bank',
                              ifelse(seller2 %like% 'Wells Fargo' | seller2 %like% 'Well Fargo'
                                     | seller2 %like% 'Fargo Bank' | seller2 %in% c('Wells, Fargo Bank Na', 'Fargo Bk'),
                                     'Wells Fargo Bank',
                                     ifelse(seller2 %like% '^Deutsche' | seller2 %in% c('Deustche Bank Natl T Co', 'America Deutsc Bk T Co Tr', 'Americas Deutsche Bk T Co',
                                                                                        'Deitsche Bk Natl T Co Tr', 'Deursche Bk Natl T Co Tr',
                                                                                        'Deustche Bk Natl T Co Tr', 'Deutache Bk Natl T Co Tr', 'Deutche Bk National T Co',
                                                                                        'Deutche Bk Natl T Co T', 'Deutshce Bk Natl T Co Tr'),
                                            'Deutsche Bank National Trust Company',
                                            ifelse(seller2 %in% c('Bank Of America NA', 'Bank Of America NA Tr', 'Bank of America NA', 'Bk Of America NA',
                                                                  'Bank of America FSB', 'Bank Of America N A', 'Bank Of America Na', 'Bank Of America Natl Assn'),
                                                   'Bank of America',
                                                   ifelse(seller2 %like% '^HSBC',
                                                          'HSBC Bank USA',
                                                          ifelse(seller2 %in% c('Citimortgage Inc', 'Citibank NA', 'Citibank NA Tr',
                                                                                'Citifinancial Svcs Inc', 'Citifinancial Servicing', 'Citifinancial Inc'),
                                                                 'Citibank',
                                                                 ifelse(seller2 %like% 'JP Morgan' | seller2 %like% 'JPMorgan' | seller2 %like% 'Jpmorgan'
                                                                        | seller2 %in% c('JP Morgan Chase Bank NA', 'JP Morgan Chase Bk', 'JP Mmorgan Chase Bk', 'JP Morgan',
                                                                                         'JP Morgan Chase Spec Mtg', 'JP Morgan Chase Bank Tr', 'JP Mmorgan Chase Bank NA',
                                                                                         'JP Morgan Acq Home Loans', 'JP Morgan Acquis Corp', 'JP Morgan Acquisit Corp', 'JP Morgan Acquisition Co',
                                                                                         'JP Morgan Cahse Bk', 'JP Morgan Chase Bank N A', 'Jp Morgan Chase Bank NA', 'JP morgan Chase Bank NA',
                                                                                         'JP Morgan Chase Bank Na', 'JP Morgan Chase Bank Na T', 'Jp Morgan Chase Bank Tr', 'Jp Morgan Chase Bk',
                                                                                         'JP morgan Chase Bk', 'Jp Morgan Chase Bk Na', 'Jp Morgan Chase Bk Tr', 'JP Morgn Chase Bk', 'JP MorganChase Bk',
                                                                                         'JP Morgan Specialty Mtg', 'JP Morgan Mtg T', 'JP Morgan Mtg Corp', 'JP Morgan Mtg Acquistion', 'JP Morgan Mtg Acquisitio',
                                                                                         'JP Morgan Mtg Acquisit Co', '	JP Morgan Mtg Acquisit 2', 'JP Morgan Mtg Acquis Corp',
                                                                                         'JP Morgan Chase Bk NA', 'Chase Home Finance LLC', 'Chase Home Fin LLC', 'Chase Home Finace LLC	',
                                                                                         'Chase Home Finance	', 'Chase Home Finance Llc', 'Chase Home Fncl LLC	', 'Chase Mahattan Bk', 'Chase Manhattan Bank USA',
                                                                                         'Chase Manhattan Mtg', 'Chase Manhattan Bk', 'Chase Manhattan Bank', 'Chas Manhattan Bk', 'Chase Manhattan Mortgage', 'Chase Manhattanmtg',
                                                                                         'Chase Mortgage Co', 'Chase Mtg', 'Chase Mtg Co', 'Chase Mtg Co West', 'Chase Mtg Holdings Inc', 'Chase Bk', 'Chase Bk TX',
                                                                                         'Chase Bk Tx', 'Jp, Morgan Chase Bank Na', 'Morgan Chase Ban Jp Tr', 'J P Morgan Chase Bank Tr',
                                                                                         'J P Morgan Chase Bank', 'J P morgan Chase Bank', 'J P Morgan Chase Bank N A'),
                                                                        'JPMorgan Chase Bank',
                                                                        ifelse(seller2 %like% '^Morgan Stanley',
                                                                               'Morgan Stanley Investment Bank',
                                                                               ifelse(seller2 %in% c('Wachovia Bk', 'Wachovia Mtg', 'Wachovia Mortgage Corp', 'Wachovia Bk NA Tr',
                                                                                                     'Wachovia Bk NA'),
                                                                                      'Wachovia Bank',
                                                                                      ifelse(seller2 %in% c('Lasalle NB', 'Lasalle Natl Bk', 'Lasalle Natl Bank', 'Lasalle National Bk Tr', 'Lasalle National Bank',
                                                                                                            'Lasalle Bk Tr', 'Lasalle Bk NA Tr', 'Lasalle Bk Na Tr', 'Lasalle Bk NA', 'Lasalle Bk Na', 'Lasalle Bk',
                                                                                                            'Lasalle Bank Tr', 'Lasalle Bank Natl Assoc', 'Lasalle Bank Natl Assn Tr', 'Lasalle Bank Natl Assn T',
                                                                                                            'Lasalle Bank National, io', 'Lasalle Bank National', 'Lasalle Bank NA Tr', 'Lasalle Bank Na Tr',
                                                                                                            'LaSalle Bank NA', 'Lasalle Bank NA', 'Lasalle Bank Na', 'Lasalle Bank N A', 'Lasalle Bank'),
                                                                                             'LaSalle Bank',
                                                                                             ifelse(seller2 %like% '^National City',
                                                                                                    'National City Bank',
                                                                                                    ifelse(seller2 %in% c('Bank Of New York', 'Bank Of New York Tr', 'Bank Of NY', 'Bank of New York',
                                                                                                                          'Bank Of New York T Co', 'Bank Of New York Mellon', 'Bank of New York Mellon',
                                                                                                                          'Bank New York Mellon Tr', 'Bk Of New York Mellon Co', 'Bk Of New York T Co NA Tr',
                                                                                                                          'Bank 0f New York', 'Bank New York', 'Bank New York Mellon', 'Bank New York Mellon T Co',
                                                                                                                          'Bank Of New New York', 'Bank Of New York  Mellon', 'Bank Of New York Mellon T',
                                                                                                                          'Bank Of New York Melon', 'Bank Of New York T', 'Bank of New York Tr',
                                                                                                                          'Bank Of New York Tr Co Tr', 'Bank of New Yorkj', 'Bank Of New Yrok', 'Bank Of NY Mellon',
                                                                                                                          'Bank Of NY Mellon T Co Tr', 'Bank Of NY Mellon Tr', 'Bank Of York Mellon', 'Banko Of New York Mellon'),
                                                                                                           'The Bank of New York Mellon',
                                                                                                           ifelse(seller2 %in% c("GMAC Mortgage LLC", 'GMAC Mtg Corp', 'GMAC Mortgage Corp', 'Gmac Mortgage Corp'),
                                                                                                                  'GMAC Mortgage Corp',
                                                                                                                  ifelse(seller2 %in% c('PNC Bank NA', 'PNC Mortgage', 'PNC Bk', 'PNC Bk NA'),
                                                                                                                         'PNC Bank',
                                                                                                                         ifelse(seller2 %in% c('Norwest Bk', 'Norwest BK', 'Norwest Bk Minn NA Tr', 'Norwest Bk Minnesota',
                                                                                                                                               'Norwest Bk Minnesota N', 'Norwest Bk Mn', 'Norwest Bk MN',
                                                                                                                                               'Norwest Bank', 'Norwest Bank Minn Na', 'Norwest Bank Minnesota', 'Norwest Bank Minnesota Na',
                                                                                                                                               'Norwest Bank MN', 'Norwest Bank Mn Na', 'Norwest Fincl Mass Inc', 'Norwest Fncl Mass',
                                                                                                                                               'Norwest Mtg', 'Norwest Mtg Corp', 'Norwest Mtg Inc'),
                                                                                                                                'Wells Fargo Bank', # Norwest Bank was acquired by Wells Fargo in 1998 and assumed the Wells Fargo name
                                                                                                                                ifelse(seller2 %like% '^American Home Mtg',
                                                                                                                                       'American Home Mortgage',
                                                                                                                                       ifelse(seller2 %in% c('FNMA', 'Federal National Mtg', 'Federal National Mtg Assn',
                                                                                                                                                             'Federal National Mtg Asso', '	Federal Natl Mtg', 'Federal National, ciatio',
                                                                                                                                                             'Federal Natl Mtg Assc', 'Federal Natl Mtg Assn', 'Federal Natl Mtg Assoc',
                                                                                                                                                             'Federal Ntl Mtg Assoc', 'Federal Ntl Mtg Associat', 'Federal Ntnl Mtg Assoc'), 'Federal National Mortgage Association (Fannie Mae)',
                                                                                                                                              ifelse(seller2 %in% c('FHLM', 'FHLMC', 'Federal Home Loan Mtg', 'Federal Home Loan Mtg Cor', 'Natl FHLM', 'Fhlm',
                                                                                                                                                                    'Federal Home Loan Mortgp', 'Federal Home Loan Corp',
                                                                                                                                                                    'Federal Home Loan', 'Fed Home Loan Mtg Corp', 'fed home loan mtg corp'), 'Federal Home Loan Mortgage Corporation (Freddie Mac)', seller2)))))))))))))))))))

  warren_adj_final = warren_adj %>%
  mutate(buyer1_adj = toupper(buyer1_adj),
         buyer2_adj = toupper(buyer2_adj),
         seller1_adj = toupper(seller1_adj),
         seller2_adj = toupper(seller2_adj))


rm(warren_df, warren_temp, warren_adj)
#change file name here (same as input file but add _adjusted)
fwrite(warren_adj_final, "20240328_warren_speculative-investment-analysis-dataset_adjusted.csv")
